#!/usr/bin/env python3
"""Appendix table behind Figure 3 (paper/plot_rlhammer.py): per-epoch ASR of the two attacker runs per target and
their mean -- exactly the numbers the curves are drawn from -- plus endpoint summaries.

    conda activate agentdojo && python paper/tab_rlhammer.py   ->  paper/tab_rlhammer.tex
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_rlhammer import series, mean_band, STEPS_PER_EPOCH  # noqa: E402

HERE = Path(__file__).resolve().parent
TARGETS = [  # (column label, run-1 spec, run-2 spec) -- identical to main() in plot_rlhammer.py
    ("Llama-3.1-8B-Instruct", "iclr_rlh_llama_base_", "iclr_rlh_llama_base_r3_"),
    ("Meta-SecAlign-8B", "eval_rl_hammer_target_meta_secalign_8b_allckpts_",
     "eval_rl_hammer_target_meta_secalign_8b_allckpts_rerun2_"),
    ("SR-Agent (Llama)", ("iclr_rlh_srllama_noappend_", "origin/exp/rlh-sr-llama"), "iclr_rlh_srllama_noappend_r2_"),
    ("Qwen3-8B", "eval_rl_hammer_target_llama_qwen_20epoch_YYN_allckpts_",
     "eval_rl_hammer_target_llama_qwen_20epoch_YYN_rrreun_allckpts_"),
    ("SR-Agent (Qwen3-8B)", "YYY1", "YYY2"),
]


def main():
    cols = []
    for label, a, b in TARGETS:
        ra, rb = series(a), series(b)
        if not ra or not rb:
            raise SystemExit(f"missing data for {label}")
        ep, mean, lo, hi = mean_band(ra, rb)
        common = sorted(set(ra) & set(rb))
        cols.append((label, ep, mean, [100 * ra[c] for c in common], [100 * rb[c] for c in common]))
    epochs = sorted(set(e for c in cols for e in c[1]))   # union grid; a target missing an epoch prints "--"
    for c in cols:
        if c[1] != epochs:
            print(f"note: {c[0]} has {len(c[1])} of {len(epochs)} epochs (missing {sorted(set(epochs) - set(c[1]))})")
    def at(c, k, which):   # value of column c at epoch index k, or None
        e = epochs[k]
        if e not in c[1]:
            return None
        return c[which][c[1].index(e)]

    L = []
    L.append("% Per-epoch numbers behind Figure~\\ref{fig:rlhammer}. Generated by paper/tab_rlhammer.py from the same run")
    L.append("% directories as paper/plot_rlhammer.py; the plotted curve is the Mean column, the band spans R1 and R2.")
    L.append("\\begin{table}[t]")
    L.append("\\centering\\scriptsize\\setlength{\\tabcolsep}{3.2pt}")
    L.append("\\caption{\\textbf{RL-Hammer attack success rate (\\%) per attacker training epoch.} For every target we ran two "
             "independent attacker trainings (R1, R2; different seeds, identical protocol) and evaluated each epoch's "
             "checkpoint on the same 100 InjecAgent test cases. Figure~\\ref{fig:rlhammer} plots the Mean column and shades "
             "the R1--R2 range. The last rows summarise the endpoint: final-epoch mean and the two runs, the mean over the "
             "last five epochs, and the peak of the mean curve.}")
    L.append("\\label{tab:rlhammer}")
    L.append("\\begin{tabular}{r" + "ccc" * len(cols) + "}")
    L.append("\\toprule")
    L.append("& " + " & ".join(f"\\multicolumn{{3}}{{c}}{{\\textbf{{{c[0]}}}}}" for c in cols) + " \\\\")
    L.append(" ".join(f"\\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(cols))))
    L.append("\\textbf{Epoch} & " + " & ".join("Mean & R1 & R2" for _ in cols) + " \\\\")
    L.append("\\midrule")
    for k, e in enumerate(epochs):
        cells = []
        for c in cols:
            m, r1, r2 = at(c, k, 2), at(c, k, 3), at(c, k, 4)
            cells.append("-- & -- & --" if m is None else f"\\textbf{{{m:.1f}}} & {r1:.0f} & {r2:.0f}")
        L.append(f"{e:.0f} & " + " & ".join(cells) + " \\\\")
    L.append("\\midrule")
    def row(name, fn):
        return f"{name} & " + " & ".join(fn(c) for c in cols) + " \\\\"
    L.append(row("Final (mean / R1 / R2)", lambda c: f"\\textbf{{{c[2][-1]:.1f}}} & {c[3][-1]:.0f} & {c[4][-1]:.0f}"))
    L.append(row("Mean of last 5 epochs", lambda c: f"\\multicolumn{{3}}{{c}}{{{sum(c[2][-5:]) / 5:.1f}}}"))
    L.append(row("Peak of mean curve", lambda c: f"\\multicolumn{{3}}{{c}}{{{max(c[2]):.1f} (ep.~{c[1][c[2].index(max(c[2]))]:.0f})}}"))
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    (HERE / "tab_rlhammer.tex").write_text("\n".join(L) + "\n")
    print(f"{'target':24s} {'final mean':>10s} {'R1':>4s} {'R2':>4s} {'last5':>6s} {'peak':>5s}")
    for label, ep, mean, r1, r2 in cols:
        print(f"{label:24s} {mean[-1]:10.1f} {r1[-1]:4.0f} {r2[-1]:4.0f} {sum(mean[-5:])/5:6.1f} {max(mean):5.1f}")
    print(f"epochs: {epochs[0]:.0f}..{epochs[-1]:.0f} ({len(epochs)} points)")


if __name__ == "__main__":
    main()
