#!/usr/bin/env python3
"""Appendix table behind Figure 3 (paper/plot_rlhammer.py): per-epoch ASR of the two attacker runs per target and
their mean -- exactly the numbers the curves are drawn from -- plus endpoint summaries.

    conda activate agentdojo && python paper/tab_rlhammer.py   ->  paper/tab_rlhammer.tex
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_rlhammer import series, mean_band, STEPS_PER_EPOCH  # noqa: E402

HERE = Path(__file__).resolve().parent
TARGETS = [  # (column label, run-1 spec, run-2 spec) -- identical to main() in plot_rlhammer.py
    ("Llama-3.1-8B-Instruct", "iclr_rlh_llama_base_", "iclr_rlh_llama_base_r3_"),
    ("Meta-SecAlign-8B", "eval_rl_hammer_target_meta_secalign_8b_allckpts_",
     "eval_rl_hammer_target_meta_secalign_8b_allckpts_rerun2_"),
    ("SR-Agent (Llama)", ("iclr_rlh_srllama_noappend_", "origin/exp/rlh-sr-llama"), "iclr_rlh_srllama_noappend_r2_"),
    ("Qwen3-8B", "eval_rl_hammer_target_llama_qwen_20epoch_YYN_allckpts_",
     "eval_rl_hammer_target_llama_qwen_20epoch_YYN_rrreun_allckpts_"),
    ("SR-Agent (Qwen3-8B)", "YYY1", "YYY2"),
]


def main():
    cols = []
    for label, a, b in TARGETS:
        ra, rb = series(a), series(b)
        if not ra or not rb:
            raise SystemExit(f"missing data for {label}")
        ep, mean, lo, hi = mean_band(ra, rb)
        common = sorted(set(ra) & set(rb))
        cols.append((label, ep, mean, [100 * ra[c] for c in common], [100 * rb[c] for c in common]))
    epochs = sorted(set(e for c in cols for e in c[1]))   # union grid; a target missing an epoch prints "--"
    for c in cols:
        if c[1] != epochs:
            print(f"note: {c[0]} has {len(c[1])} of {len(epochs)} epochs (missing {sorted(set(epochs) - set(c[1]))})")
    def at(c, k, which):   # value of column c at epoch index k, or None
        e = epochs[k]
        if e not in c[1]:
            return None
        return c[which][c[1].index(e)]

    L = []
    L.append("% Endpoint statistics of the curves in Figure~\\ref{fig:rlhammer}. Generated by paper/tab_rlhammer.py from the same run")
    L.append("% directories as paper/plot_rlhammer.py; every number is the mean over the two attacker runs.")
    L.append("\\begin{table}[t]")
    L.append("\\centering\\small\\setlength{\\tabcolsep}{8pt}")
    L.append("\\caption{\\textbf{RL-Hammer attack success rate (\\%): endpoint statistics of Figure~\\ref{fig:rlhammer}.} "
             "Each value is the mean over two independent attacker trainings against that target (different seeds, identical "
             "protocol), with every epoch's checkpoint evaluated on the same 100 InjecAgent test cases. Final = the last attacker "
             "epoch; Last-5 = mean over the last five epochs; Peak = maximum of the curve and the epoch at which it occurs.}")
    L.append("\\label{tab:rlhammer}")
    L.append("\\begin{tabular}{llccc}")
    L.append("\\toprule")
    L.append("\\textbf{Family} & \\textbf{Target} & \\textbf{Final} $\\downarrow$ & \\textbf{Last-5} $\\downarrow$ & \\textbf{Peak (epoch)} $\\downarrow$ \\\\")
    L.append("\\midrule")
    fam = {"Llama-3.1-8B-Instruct": "Llama-3.1-8B", "Meta-SecAlign-8B": "Llama-3.1-8B", "SR-Agent (Llama)": "Llama-3.1-8B",
           "Qwen3-8B": "Qwen3-8B", "SR-Agent (Qwen3-8B)": "Qwen3-8B"}
    label_tex = {"SR-Agent (Llama)": "SR-Agent (ours)", "SR-Agent (Qwen3-8B)": "SR-Agent (ours)",
                 "Llama-3.1-8B-Instruct": "Undefended base", "Qwen3-8B": "Undefended base"}
    prev = None
    for label, ep, mean, r1, r2 in cols:
        f = fam[label]
        if prev is not None and f != prev:
            L.append("\\midrule")
        first = f"\\multirow{{{sum(1 for c in cols if fam[c[0]] == f)}}}{{*}}{{{f}}}" if f != prev else ""
        name = label_tex.get(label, label)
        bold = lambda x: f"\\textbf{{{x}}}" if label.startswith("SR-Agent") else x
        L.append(f"{first} & {name} & {bold(f'{mean[-1]:.1f}')} & {bold(f'{sum(mean[-5:]) / 5:.1f}')} & "
                 f"{bold(f'{max(mean):.1f} ({ep[mean.index(max(mean))]:.0f})')} \\\\")
        prev = f
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    (HERE / "tab_rlhammer.tex").write_text("\n".join(L) + "\n")
    print(f"{'target':24s} {'final mean':>10s} {'R1':>4s} {'R2':>4s} {'last5':>6s} {'peak':>5s}")
    for label, ep, mean, r1, r2 in cols:
        print(f"{label:24s} {mean[-1]:10.1f} {r1[-1]:4.0f} {r2[-1]:4.0f} {sum(mean[-5:])/5:6.1f} {max(mean):5.1f}")
    print(f"epochs: {epochs[0]:.0f}..{epochs[-1]:.0f} ({len(epochs)} points)")


if __name__ == "__main__":
    main()
