#!/usr/bin/env python3
"""Appendix subsubsection for the train-time ablation: prose + endpoint-statistics table in ONE file.

Statistics follow paper/tab_rlhammer.py exactly -- mean over the attacker runs first, then Final / Last-5 / Peak.
Every number in the prose is interpolated from the same data as the table, so regenerating cannot leave the two out of
step; edit this script rather than the .tex.

    conda activate agentdojo && python paper/tab_ablation.py   ->  paper/sec_ablation_appendix.tex
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_ablation import CURVES, mean_band  # noqa: E402

HERE = Path(__file__).resolve().parent
BOLD = {"SR-Agent (ours)"}


def main():
    rows = []
    for label, _color, _marker, _ls, names in CURVES:
        ep, mean, _lo, _hi = mean_band(names)
        rows.append((label, len(names), ep, mean))

    stat = {lab: (m[-1], sum(m[-5:]) / 5, max(m), e[m.index(max(m))]) for lab, _n, e, m in rows}
    base = stat["Undefended base"]; sr = stat["SR-Agent (ours)"]
    on = stat["w/o reflection, think on"]; off = stat["w/o reflection, think off"]
    ratio = (on[0] + off[0]) / 2 / sr[0]

    L = []
    L.append("% Appendix subsubsection for the train-time ablation: prose and table. GENERATED by paper/tab_ablation.py")
    L.append("% from the same run directories as paper/plot_ablation.py -- regenerate it rather than editing numbers here.")
    L.append("")
    L.append("\\subsubsection{Train-Time Ablation: Endpoint Statistics}")
    L.append("\\label{app:train_time_ablation}")
    L.append("")
    L.append("Table~\\ref{tab:train_time_ablation} gives the endpoint statistics of the curves in")
    L.append("Figure~\\ref{fig:train_time_ablation}, using the same conventions as Table~\\ref{tab:rlhammer}. The undefended base and")
    L.append("SR-Agent rows repeat the Qwen3-8B entries of that table and are the mean of two independent attacker trainings; the two")
    L.append("ablation rows are single attacker trainings against the model trained without reflection, and differ only in the")
    L.append("target's thinking mode, which is held consistent between attacker training and target evaluation.")
    L.append("")
    L.append(f"The two ablation settings end at the same point, ${on[0]:.1f}\\%$, within a point of the undefended base's")
    L.append(f"${base[0]:.1f}\\%$ and roughly {ratio:.1f} times SR-Agent's ${sr[0]:.1f}\\%$. That the two settings agree is what makes the")
    L.append("rows interpretable: the model trained without reflection is equally exposed whether or not it is asked to think at")
    L.append("inference, so its vulnerability follows from the missing reflection supervision rather than from any distribution")
    L.append("shift introduced at evaluation time. The remaining difference between the two is in shape rather than level ---")
    L.append(f"with thinking enabled the attacker peaks at epoch {on[3]:.0f} against epoch {off[3]:.0f} without it --- which is why the")
    L.append("Last-5 means differ slightly while the final values do not.")
    L.append("")
    L.append("\\begin{table}[t]")
    L.append("\\centering\\small\\setlength{\\tabcolsep}{8pt}")
    L.append("\\caption{\\textbf{Train-time ablation, attack success rate (\\%): endpoint statistics of "
             "Figure~\\ref{fig:train_time_ablation}.} All targets are Qwen3-8B and every attacker checkpoint is evaluated on "
             "the same 100 InjecAgent test cases. The undefended base and SR-Agent are the mean over two independent attacker "
             "trainings; the two ablation rows are single attacker trainings against the same checkpoint, differing only in the "
             "target's thinking mode, which is held consistent between attacker training and evaluation. Final = the last "
             "attacker epoch; Last-5 = mean over the last five epochs; Peak = maximum of the curve and the epoch at which it "
             "occurs. \\#Runs is the number of attacker trainings averaged.}")
    L.append("\\label{tab:train_time_ablation}")
    L.append("\\begin{tabular}{lcccc}")
    L.append("\\toprule")
    L.append("\\textbf{Target} & \\textbf{\\#Runs} & \\textbf{Final} $\\downarrow$ & \\textbf{Last-5} $\\downarrow$ & "
             "\\textbf{Peak (epoch)} $\\downarrow$ \\\\")
    L.append("\\midrule")
    for i, (label, nruns, ep, mean) in enumerate(rows):
        if i == 2:
            L.append("\\midrule")
        b = (lambda x: f"\\textbf{{{x}}}") if label in BOLD else (lambda x: x)
        peak = max(mean)
        L.append(f"{label} & {nruns} & {b(f'{mean[-1]:.1f}')} & {b(f'{sum(mean[-5:]) / 5:.1f}')} & "
                 f"{b(f'{peak:.1f} ({ep[mean.index(peak)]:.0f})')} \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    (HERE / "sec_ablation_appendix.tex").write_text("\n".join(L) + "\n")

    print(f"{'target':28s}{'runs':>5}{'final':>8}{'last5':>8}{'peak':>8}{'epoch':>7}")
    for label, nruns, ep, mean in rows:
        pk = max(mean)
        print(f"{label:28s}{nruns:>5}{mean[-1]:>8.1f}{sum(mean[-5:])/5:>8.1f}{pk:>8.1f}{ep[mean.index(pk)]:>7.0f}")
    print("-> paper/sec_ablation_appendix.tex")


if __name__ == "__main__":
    main()
