#!/usr/bin/env python3
"""Appendix table behind the train-time ablation figure (paper/plot_ablation.py): endpoint statistics of the same
curves, computed exactly as paper/tab_rlhammer.py does -- mean over the attacker runs first, then Final / Last-5 / Peak.

    conda activate agentdojo && python paper/tab_ablation.py   ->  paper/tab_ablation.tex
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_ablation import CURVES, mean_band  # noqa: E402

HERE = Path(__file__).resolve().parent
BOLD = {"SR-Agent (ours)"}


def main():
    rows = []
    for label, _color, _marker, _ls, names in CURVES:
        ep, mean, _lo, _hi = mean_band(names)
        rows.append((label, len(names), ep, mean))

    L = []
    L.append("% Endpoint statistics of the curves in Figure~\\ref{fig:train_time_ablation}. Generated by paper/tab_ablation.py")
    L.append("% from the same run directories as paper/plot_ablation.py, with the same convention as Table~\\ref{tab:rlhammer}:")
    L.append("% the two-run targets are averaged first, then Final / Last-5 / Peak are read off that mean curve.")
    L.append("\\begin{table}[t]")
    L.append("\\centering\\small\\setlength{\\tabcolsep}{8pt}")
    L.append("\\caption{\\textbf{Train-time ablation, attack success rate (\\%): endpoint statistics of "
             "Figure~\\ref{fig:train_time_ablation}.} All targets are Qwen3-8B and every attacker checkpoint is evaluated on "
             "the same 100 InjecAgent test cases. The undefended base and SR-Agent are the mean over two independent attacker "
             "trainings; the two ablation rows are single attacker trainings against the same checkpoint, differing only in the "
             "target's thinking mode, which is held consistent between attacker training and evaluation. Final = the last "
             "attacker epoch; Last-5 = mean over the last five epochs; Peak = maximum of the curve and the epoch at which it "
             "occurs. \\#Runs is the number of attacker trainings averaged.}")
    L.append("\\label{tab:train_time_ablation}")
    L.append("\\begin{tabular}{lcccc}")
    L.append("\\toprule")
    L.append("\\textbf{Target} & \\textbf{\\#Runs} & \\textbf{Final} $\\downarrow$ & \\textbf{Last-5} $\\downarrow$ & "
             "\\textbf{Peak (epoch)} $\\downarrow$ \\\\")
    L.append("\\midrule")
    for i, (label, nruns, ep, mean) in enumerate(rows):
        if i == 2:
            L.append("\\midrule")
        b = (lambda x: f"\\textbf{{{x}}}") if label in BOLD else (lambda x: x)
        peak = max(mean)
        L.append(f"{label} & {nruns} & {b(f'{mean[-1]:.1f}')} & {b(f'{sum(mean[-5:]) / 5:.1f}')} & "
                 f"{b(f'{peak:.1f} ({ep[mean.index(peak)]:.0f})')} \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    (HERE / "tab_ablation.tex").write_text("\n".join(L) + "\n")

    print(f"{'target':28s}{'runs':>5}{'final':>8}{'last5':>8}{'peak':>8}{'epoch':>7}")
    for label, nruns, ep, mean in rows:
        pk = max(mean)
        print(f"{label:28s}{nruns:>5}{mean[-1]:>8.1f}{sum(mean[-5:])/5:>8.1f}{pk:>8.1f}{ep[mean.index(pk)]:>7.0f}")
    print("-> paper/tab_ablation.tex")


if __name__ == "__main__":
    main()
