#!/usr/bin/env python3
"""Appendix table behind Figure 3 (paper/plot_rlhammer.py): per-epoch ASR of the two attacker runs per target and
their mean -- exactly the numbers the curves are drawn from -- plus endpoint summaries.

    conda activate agentdojo && python paper/tab_rlhammer.py   ->  paper/tab_rlhammer.tex
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plot_rlhammer import series, mean_band, STEPS_PER_EPOCH  # noqa: E402

HERE = Path(__file__).resolve().parent
TARGETS = [  # (column label, run-1 spec, run-2 spec) -- identical to main() in plot_rlhammer.py
    ("Llama-3.1-8B-Instruct", "iclr_rlh_llama_base_", "iclr_rlh_llama_base_r3_"),
    ("Meta-SecAlign-8B", "eval_rl_hammer_target_meta_secalign_8b_allckpts_",
     "eval_rl_hammer_target_meta_secalign_8b_allckpts_rerun2_"),
    ("SR-Agent (Llama)", ("iclr_rlh_srllama_noappend_", "origin/exp/rlh-sr-llama"), "iclr_rlh_srllama_noappend_r2_"),
    ("Qwen3-8B", "eval_rl_hammer_target_llama_qwen_20epoch_YYN_allckpts_",
     "eval_rl_hammer_target_llama_qwen_20epoch_YYN_rrreun_allckpts_"),
    ("SR-Agent (Qwen3-8B)", "YYY1", "YYY2"),
]


def main():
    cols = []
    for label, a, b in TARGETS:
        ra, rb = series(a), series(b)
        if not ra or not rb:
            raise SystemExit(f"missing data for {label}")
        ep, mean, lo, hi = mean_band(ra, rb)
        common = sorted(set(ra) & set(rb))
        cols.append((label, ep, mean, [100 * ra[c] for c in common], [100 * rb[c] for c in common]))
    epochs = sorted(set(e for c in cols for e in c[1]))   # union grid; a target missing an epoch prints "--"
    for c in cols:
        if c[1] != epochs:
            print(f"note: {c[0]} has {len(c[1])} of {len(epochs)} epochs (missing {sorted(set(epochs) - set(c[1]))})")
    def at(c, k, which):   # value of column c at epoch index k, or None
        e = epochs[k]
        if e not in c[1]:
            return None
        return c[which][c[1].index(e)]

    L = []
    L.append("% Per-epoch numbers behind Figure~\\ref{fig:rlhammer}. Generated by paper/tab_rlhammer.py from the same run")
    L.append("% directories as paper/plot_rlhammer.py; each cell is the mean over the two attacker runs, i.e. the plotted curve.")
    L.append("\\begin{table}[t]")
    L.append("\\centering\\small\\setlength{\\tabcolsep}{6pt}")
    L.append("\\caption{\\textbf{RL-Hammer attack success rate (\\%) per attacker training epoch.} Each value is the mean over two "
             "independent attacker trainings against that target (different seeds, identical protocol), each epoch's checkpoint "
             "evaluated on the same 100 InjecAgent test cases; these are the values plotted in Figure~\\ref{fig:rlhammer}. "
             "The summary rows give the final epoch, the mean over the last five epochs, the peak of the curve, and the "
             "spread between the two runs at the final epoch.}")
    L.append("\\label{tab:rlhammer}")
    L.append("\\begin{tabular}{r" + "c" * len(cols) + "}")
    L.append("\\toprule")
    L.append("\\textbf{Epoch} & " + " & ".join(f"\\textbf{{{c[0]}}}" for c in cols) + " \\\\")
    L.append("\\midrule")
    for k, e in enumerate(epochs):
        cells = []
        for c in cols:
            m, r1, r2 = at(c, k, 2), at(c, k, 3), at(c, k, 4)
            cells.append("--" if m is None else f"{m:.1f}")
        L.append(f"{e:.0f} & " + " & ".join(cells) + " \\\\")
    L.append("\\midrule")
    def row(name, fn):
        return f"{name} & " + " & ".join(fn(c) for c in cols) + " \\\\"
    L.append(row("Final epoch", lambda c: f"\\textbf{{{c[2][-1]:.1f}}}"))
    L.append(row("Mean of last 5 epochs", lambda c: f"{sum(c[2][-5:]) / 5:.1f}"))
    L.append(row("Peak (epoch)", lambda c: f"{max(c[2]):.1f} ({c[1][c[2].index(max(c[2]))]:.0f})"))
    L.append(row("Run-to-run spread at final epoch", lambda c: f"$\\pm${abs(c[3][-1] - c[4][-1]) / 2:.1f}"))
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    (HERE / "tab_rlhammer.tex").write_text("\n".join(L) + "\n")
    print(f"{'target':24s} {'final mean':>10s} {'R1':>4s} {'R2':>4s} {'last5':>6s} {'peak':>5s}")
    for label, ep, mean, r1, r2 in cols:
        print(f"{label:24s} {mean[-1]:10.1f} {r1[-1]:4.0f} {r2[-1]:4.0f} {sum(mean[-5:])/5:6.1f} {max(mean):5.1f}")
    print(f"epochs: {epochs[0]:.0f}..{epochs[-1]:.0f} ({len(epochs)} points)")


if __name__ == "__main__":
    main()
